
// Type: com.digitalarcsystems.Traveller.CreationOperation




#nullable disable
namespace com.digitalarcsystems.Traveller
{
  public enum CreationOperation
  {
    UNDEFINED,
    SELECT_RACE,
    GENERATE_STATS,
    CHOOSE_HOMEWORLD,
    GAIN_BACKGROUND_SKILLS,
    HANDLE_PRECAREER,
    CHOOSE_CAREER,
    GET_BASIC_TRAINING,
    CHOOSE_CAREER_SPECIALIZATION,
    CHOOSE_SKILLS_AND_TRAINING_TABLE_OBTAIN_SKILL,
    ROLL_FOR_SURVIVAL,
    ROLL_MISHAP,
    ROLL_EVENTS,
    PROCESS_ADVANCEMENT_OR_COMISSION,
    HANDLE_AGING,
    GENERATE_MUSTERING_OUT_BENEFIT,
    HANDLE_INJURIES,
    CHOOSE_END_OF_TERM_ACTION,
    ESTABLISH_CONNECTION_WITH_OTHER_CHARCTER,
    CHOOSE_CONNECTION_SKILLS,
    SELECT_SKILL_PACKAGE,
    SELECT__SKILL_FROM_SHARED_PACKAGE,
    CHOOSE_ONE_FREE_SKILL,
    HIERATE_CHOOSE_GENDER,
    HIERATE_DETERMINE_ANCESTRAL_HISTORY,
    HIERATE_RIGHT_OF_PASSAGE,
    HIERATE_ALLOCATE_CLAN_SHARES,
    CHARACTER_FINALIZATION,
    PURCHASE_EQUIPMENT,
    FINISHED,
  }
}
